{{- if .Values.db.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "db.pvcName" . }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.db.persistence.accessModes | first | quote }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size | quote }}
  {{- if .Values.db.persistence.storageClass }}
  storageClassName: {{ .Values.db.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
