apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.secretName" . }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.db.environment }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
