apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.serviceName" . }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }} 
      targetPort: {{ .Values.db.service.targetPort }}
      protocol: {{ .Values.db.service.protocol }}
  selector:
    {{- include "db.labels" . | nindent 4 }}
