README:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

docker-compose:
- changed-files:
  - any-glob-to-any-file: '**/docker-compose.yml'

dockerfile:
- changed-files:
  - any-glob-to-any-file: '**/Dockerfile'


requirements:
- changed-files:
  - any-glob-to-any-file: '**/requirements.txt'

gpt:
- changed-files:
  - any-glob-to-any-file: '**/app/gpt_services.py'

fastapi:
- changed-files:
  - any-glob-to-any-file: '**/app/main.py'

prompt:
- changed-files:
  - any-glob-to-any-file: '**/app/prompt_generators.py'

