README:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

docker-compose:
- changed-files:
  - any-glob-to-any-file: '**/docker-compose.yml'

dockerfile:
- changed-files:
  - any-glob-to-any-file: '**/Dockerfile'
