apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-helm.fullname" . }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ include "my-helm.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-helm.name" . }}
    spec:
      containers:
        - name: {{ include "my-helm.name" . }}
          image: {{ .Values.web.image }}
          ports:
            - containerPort: {{ .Values.web.service.port }}
          env:
            - name: ENV1
              value: Hi
