apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myhelm-chart.fullname" . }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ include "myhelm-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "myhelm-chart.name" . }}
    spec:
      containers:
      - name: {{ include "myhelm-chart.name" . }}
        image: {{ .Values.web.image }}
        ports:
        - containerPort: 80
        env:
        {{- range .Values.web.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
