apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "MyHelm.fullname" . }}-web
spec:
  replicas: {{ .Values.web.replicas }}
  template:
    metadata:
      labels:
        app: {{ include "MyHelm.name" . }}
    spec:
      containers:
        - name: web
          image: {{ .Values.web.image }}
          ports:
            - containerPort: {{ .Values.web.service.targetPort }}
          env:
          {{- range .Values.web.env }}
            - name: {{ .name }}
              value: {{ .value }}
          {{- end }}
