apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.service.port }}
  selector:
    app: {{ include "my-helm.name" . }}
