apiVersion: v1
kind: Service
metadata:
  name: {{ include "MyHelm.fullname" . }}-web
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.service.targetPort }}
  selector:
    app: {{ include "MyHelm.name" . }}
