apiVersion: v1
kind: Service
metadata:
  name: {{ include "myhelm-chart.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ include "myhelm-chart.name" . }}
