web:
  env:
  - name: ENV1
    value: Hi
  image:
    repository: nginx
    tag: latest
  ingress:
    enabled: false
    host: www.example.com
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    size: 1Gi
  replicaCount: 1
  service:
    enabled: true
    port: 80
