apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-web-pvc
spec:
  accessModes:
    - {{ .Values.web.persistence.accessModes | first }}
  resources:
    requests:
      storage: {{ .Values.web.persistence.size }}
