apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web.secretName" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.web.environment }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
