name: Docker CI
on:
  pull_request:
    types:
      - closed
    branches:
      - master
jobs:

 CI:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    - name: install requirements
      run: pip install -r requirements.txt
      
    - name: docker login
      uses: docker/login-action@v3
      with:
        username: 81318131
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: build services
      run: docker compose build
      
    - name: run services
      run: sh run.sh
      
    - name: stop containers
      run: docker compose down
